### ISSUE TITLE
USER STORY: BASIC HTML STRUCTURE IN PLACE

### ISSUE THREAD

**Issue by markolejman** [markohautala/e-commerce-v1#2]
As a **User** I can **scroll through different pages and explore the footer/header** so that **I can do different things on the website**

## Acceptance criteria:
- 3 HTML pages in place
- A footer with some social media icons
- Header in place with a logo of the company

## Tasks:
- [ ] Create the main html-page
- [ ] Add some styling and icons to the footer
- [ ] duplicate the pages and connect them
- [ ] add company logo to header and add the links to the other html-pages
